# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15storage_service.proto\x12\x0fstorage_service\":\n\nPutRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"D\n\x0bPutResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t2V\n\x0eStorageService\x12\x44\n\x03Put\x12\x1b.storage_service.PutRequest\x1a\x1c.storage_service.PutResponse\"\x00(\x01\x42\x0eZ\x0c./storage_gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./storage_go'
  _globals['_PUTREQUEST']._serialized_start=42
  _globals['_PUTREQUEST']._serialized_end=100
  _globals['_PUTRESPONSE']._serialized_start=102
  _globals['_PUTRESPONSE']._serialized_end=170
  _globals['_STORAGESERVICE']._serialized_start=172
  _globals['_STORAGESERVICE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
